# disable sudo to speed up the build
sudo: false

language: python
python:
  - "3.6"

cache:
  pip
install:
  - pip install coverage
  - pip install codecov

script:
  - python -m unittest discover
  - coverage run -m unittest discover
  - coverage report --omit=*test*
  
env:
  - CODECOV_TOKEN="aaa4075d-6496-44a9-baf9-ba8d86abf468"
  
# Push results back to codecov
after_success: 
  - codecov

  
